from django.conf.urls import url
from . import views

app_name = 'archiv'

urlpatterns = [
    url(r'^communication/detail/(?P<pk>[0-9]+)$', views.CommunicationDetailView.as_view(),
        name='communication_detail'),
    url(r'^communication/create/$', views.CommunicationCreate.as_view(),
        name='communication_create'),
    url(r'^communication/edit/(?P<pk>[0-9]+)$', views.CommunicationUpdate.as_view(),
        name='communication_edit'),
    url(r'^communication/delete/(?P<pk>[0-9]+)$', views.CommunicationDelete.as_view(),
        name='communication_delete'),
    url(r'^extractionarea/detail/(?P<pk>[0-9]+)$', views.ExtractionAreaDetailView.as_view(),
        name='extractionarea_detail'),
    url(r'^extractionarea/create/$', views.ExtractionAreaCreate.as_view(),
        name='extractionarea_create'),
    url(r'^extractionarea/edit/(?P<pk>[0-9]+)$', views.ExtractionAreaUpdate.as_view(),
        name='extractionarea_edit'),
    url(r'^extractionarea/delete/(?P<pk>[0-9]+)$', views.ExtractionAreaDelete.as_view(),
        name='extractionarea_delete'),
    url(r'^settlement/detail/(?P<pk>[0-9]+)$', views.SettlementDetailView.as_view(),
        name='settlement_detail'),
    url(r'^settlement/create/$', views.SettlementCreate.as_view(),
        name='settlement_create'),
    url(r'^settlement/edit/(?P<pk>[0-9]+)$', views.SettlementUpdate.as_view(),
        name='settlement_edit'),
    url(r'^settlement/delete/(?P<pk>[0-9]+)$', views.SettlementDelete.as_view(),
        name='settlement_delete'),
    url(r'^site/detail/(?P<pk>[0-9]+)$', views.SiteDetailView.as_view(),
        name='site_detail'),
    url(r'^cemetery/detail/(?P<pk>[0-9]+)$', views.CemeteryDetailView.as_view(),
        name='cemetery_detail'),
    url(r'^cemetery/create/$', views.CemeteryCreate.as_view(),
        name='cemetery_create'),
    url(r'^cemetery/edit/(?P<pk>[0-9]+)$', views.CemeteryUpdate.as_view(),
        name='cemetery_edit'),
    url(r'^cemetery/delete/(?P<pk>[0-9]+)$', views.CemeteryDelete.as_view(),
        name='cemetery_delete'),
    url(r'^site/create/$', views.SiteCreate.as_view(),
        name='site_create'),
    url(r'^site/edit/(?P<pk>[0-9]+)$', views.SiteUpdate.as_view(),
        name='site_edit'),
    url(r'^site/delete/(?P<pk>[0-9]+)$', views.SiteDelete.as_view(),
        name='site_delete'),
    url(r'^period/detail/(?P<pk>[0-9]+)$', views.PeriodDetailView.as_view(),
        name='period_detail'),
    url(r'^period/create/$', views.PeriodCreate.as_view(),
        name='period_create'),
    url(r'^period/edit/(?P<pk>[0-9]+)$', views.PeriodUpdate.as_view(),
        name='period_edit'),
    url(r'^period/delete/(?P<pk>[0-9]+)$', views.PeriodDelete.as_view(),
        name='period_delete'),
    url(r'^altname/detail/(?P<pk>[0-9]+)$', views.AltNameDetailView.as_view(),
        name='altname_detail'),
    url(r'^altname/create/$', views.AltNameCreate.as_view(),
        name='altname_create'),
    url(r'^altname/edit/(?P<pk>[0-9]+)$', views.AltNameUpdate.as_view(),
        name='altname_edit'),
    url(r'^altname/delete/(?P<pk>[0-9]+)$', views.AltNameDelete.as_view(),
        name='altname_delete'),
    url(r'^researchevent/detail/(?P<pk>[0-9]+)$', views.ResearchEventDetailView.as_view(),
        name='researchevent_detail'),
    url(r'^researchevent/create/$', views.ResearchEventCreate.as_view(),
        name='researchevent_create'),
    url(r'^researchevent/edit/(?P<pk>[0-9]+)$', views.ResearchEventUpdate.as_view(),
        name='researchevent_edit'),
    url(r'^researchevent/delete/(?P<pk>[0-9]+)$', views.ResearchEventDelete.as_view(),
        name='researchevent_delete'),
]
