SITE = [
    (('identifier'), ('Identifier')),
    (('name'), ('Site Name')),
    (('alt_name'), ('Alternative Name')),
    (('alt_id'), ('Alt ID')),
    (('description'), ('Description')),
    (('comment'), ('Comment')),
    (('public'), ('Public')),
    (('literature__zotero_item__zoterokey'), ('Literatur')),
    (('cadastral_community__cadcom_nam'), ('Cadastral Community')),
    (('cadastral_number'), ('Cadastral Nummer')),
    (('heritage_number'), ('Heritage Number')),
    (('plot_number'), ('Plot Number')),
    (('ownership'), ('Ownership')),
    (('other_period__pref_label'), ('Other Period')),
    (('accessibility'), ('accessibility')),
    (('visibility'), ('visibility')),
    (('infrastructure'), ('infrastructure')),
    (('long_term_management'), ('long term management')),
    (('potential_surrounding'), ('potential surrounding')),
    (('museum__written_name'), ('Museum')),
    (('iad_app'), ('Iad App')),
    (('app_description'), ('App Description')),
    (('tourism_comment'), ('Tourism Comment')),
    (('site_checked_by__username'), ('Site checked by')),
]
