# Generated by Django 5.2.7 on 2025-11-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadata',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='skoscollection',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='skosconcept',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='skosconceptscheme',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='skoslabel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='skosnamespace',
            options={'ordering': ['id']},
        ),
    ]
