# Generated by Django 5.0.7 on 2024-07-17 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ZotItem",
            fields=[
                (
                    "zot_key",
                    models.CharField(
                        help_text="The Zotero Item Key",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="key",
                    ),
                ),
                (
                    "zot_creator",
                    models.TextField(
                        blank=True,
                        help_text="Stores all information from zoteros 'creators' field.",
                        verbose_name="creators",
                    ),
                ),
                (
                    "zot_date",
                    models.TextField(
                        blank=True,
                        help_text="Stores all information from zoteros 'date' field.",
                        verbose_name="date",
                    ),
                ),
                (
                    "zot_item_type",
                    models.TextField(
                        blank=True,
                        help_text="Stores all information from zoteros 'itemType' field.",
                        verbose_name="itemType",
                    ),
                ),
                (
                    "zot_title",
                    models.TextField(
                        blank=True,
                        help_text="Stores all information from zoteros 'title' field.",
                        verbose_name="title",
                    ),
                ),
                (
                    "zot_pub_title",
                    models.TextField(
                        blank=True,
                        help_text="Stores all information from zoteros 'publicationTitle' field.",
                        verbose_name="publicationTitle",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Stores all information from zoteros 'publicationTitle' field.",
                        null=True,
                        verbose_name="dateModified",
                    ),
                ),
                (
                    "zot_pages",
                    models.TextField(
                        blank=True,
                        help_text="Stores all information from zoteros 'pages' field.",
                        verbose_name="pages",
                    ),
                ),
                (
                    "zot_version",
                    models.IntegerField(
                        blank=True,
                        help_text="Stores all information from zoteros 'pages' field.",
                        null=True,
                        verbose_name="version",
                    ),
                ),
                (
                    "zot_html_link",
                    models.CharField(
                        blank=True,
                        help_text="Stores all information from zoteros 'selflink' field.",
                        max_length=500,
                        verbose_name="selflink html",
                    ),
                ),
                (
                    "zot_api_link",
                    models.CharField(
                        blank=True,
                        help_text="Stores all information from zoteros self api link field.",
                        max_length=500,
                        verbose_name="selflink api",
                    ),
                ),
                (
                    "zot_bibtex",
                    models.TextField(
                        blank=True,
                        help_text="Stores the item's bibtex representation.",
                        verbose_name="bibtex",
                    ),
                ),
            ],
            options={
                "ordering": ["-zot_version"],
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        blank=True,
                        help_text="Page Number",
                        max_length=250,
                        null=True,
                        verbose_name="Page Number",
                    ),
                ),
                (
                    "zotero_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the zotero item you would like to quote",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="has_references",
                        to="bib.zotitem",
                        verbose_name="Zotero Item",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
