# Generated by Django 5.2.7 on 2025-11-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idprovider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idprovider',
            options={'ordering': ['id']},
        ),
    ]
