# Generated by Django 5.0.7 on 2024-07-17 07:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lau2_id", models.CharField(blank=True, max_length=254)),
                ("lau2nam", models.CharField(blank=True, max_length=254)),
                ("nuts3cod", models.CharField(blank=True, max_length=254)),
                ("nuts3nam", models.CharField(blank=True, max_length=254)),
                ("nuts2cod", models.CharField(blank=True, max_length=254)),
                ("nuts2nam", models.CharField(blank=True, max_length=254)),
                ("ctcod", models.CharField(blank=True, max_length=254)),
                ("ctnam", models.CharField(blank=True, max_length=254)),
                ("ctalt", models.CharField(blank=True, max_length=254)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
