name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v7
      - name: Set up ruff
        uses: astral-sh/ruff-action@v4.1.0
      - name: Run ruff check
        run: ruff check 